source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DynUI_Example', :exclusive => true do
  pod "DynUI", :path => "../"
end

target 'DynUI_Tests', :exclusive => true do
  pod "DynUI", :path => "../"

#pod 'SuperSerial', :git => "https://github.com/pourhadi/SuperSerial.git"
end
